### ISSUE TITLE
Controlling Turtlesim using Novint falcon haptic device

### ISSUE THREAD

**Issue by rsabhishek-iitdh** [WPI-AIM/ros_falcon#13]
Hello,
I am new to ROS and Ubuntu I am trying to interface ros and falcon device in ROS kinetics Ubuntu 16.04. I have downloaded and installed libnifalcon but still unable to use this for turtlesim.

I am unable to install libnifalcon, can anyone advice me ?

**Comment by adnanmunawar** [comment]
Hello,

As you mentioned in your issue:
 

> I have downloaded and installed libnifalcon but still unable to use this for turtlesim

 and then you mention 

> I am unable to install libnifalcon
 
So I am not sure if you have or have not installed **libnifalcon**. There are two separate packages that are required, this package itself, which is called **ros_falcon** and then another package (library), called **libnifalcon**.

You have to get (clone, build and install) **libnifalcon** from here:

 https://github.com/libnifalcon/libnifalcon

Make sure to **install** the library. Instructions can be found here:

https://github.com/libnifalcon/libnifalcon/blob/master/COMPILE.txt

Then you can build this package.

**Comment by rsabhishek-iitdh** [comment]
Hello,
Thank you for your response. Now i could able to install libnifalcon.
Actually I am interested to interface the ROS (kinetic) with Novint falcon
haptic device there by controlling the Turtlesim wall feedback. Since I am
new ROS and haptic drivers can you please suggest me further. Thank you in
advance.

Thanks & Regards
Abhishek RS
JRF Dept. of EE
IIT Dharwad
