### ISSUE TITLE
error while loading shared libraries: libnifalcon.so.1.0.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ashk-on** [WPI-AIM/ros_falcon#2]
Hi,
I managed to compile the package and everything finished without error... However while trying to rosrun, the following happend.

/home/ashkan/catkin_ws/devel/lib/rosfalcon/joystick: error while loading shared libraries: libnifalcon.so.1.0.2: cannot open shared object file: No such file or directory

**Comment by adnanmunawar** [comment]
Did you install libnifalcon located here

https://github.com/libnifalcon/libnifalcon

**Comment by navuboy** [comment]
Is this issue resolved? Even I am facing the similar issue.

**Comment by adnanmunawar** [comment]
Did you install libnifalcon as stated on the project README page?

**Comment by navuboy** [comment]
I sorted out the issue, but thanks for the reply!

**Comment by OEspitia77** [comment]
@nav74neet , How did you solve the problem, the same thing happened to me.

**Comment by adnanmunawar** [comment]
Try running `sudo ldconfig` in your terminal and then retry

**Comment by OEspitia77** [comment]
@adnanmunawar work it, thanks a lot¡¡¡¡¡

**Comment by adnanmunawar** [comment]
Great. Closing this issue
