### ISSUE TITLE
No force generated when receiving /falconForces.

### ISSUE THREAD

**Issue by yuewei2017** [WPI-AIM/ros_falcon#4]
I use the `driver(or main)` in /src, `/falconPos` can be published correctly(it proves that the falcon runs normally), but when I published `/falconForces`,there was no response from Falcon handler.

**Comment by adnanmunawar** [comment]
Can you elaborate more about your problem

**Comment by ioarun** [comment]
This has been solved. The changes have been done in joystick.py. 
Please check my [fork](https://github.com/ioarun/ros_falcon) of this repository. 
Clone the fork in `catkin_ws/src `and build it. Then go to `catkin_ws/devel/lib/ros_falcon`. You should find joystick executable. Run` ./joystick `

**Comment by adnanmunawar** [comment]
Thank you, that's very useful. Can you please open a pull request so that I can merge your changes.

**Comment by ioarun** [comment]
I have already opened a pull request. Please merge if it's helpful.
Thanks.

**Comment by adnanmunawar** [comment]
Merged

**Comment by dChaisumdet** [comment]
Does this mean to publish forces we use the `rosrun ros_falcon joystick` instead of `rosrun ros_falcon driver`?
