### ISSUE TITLE
Build error in falcon_js_pid and falcon_cs_pid

### ISSUE THREAD

**Issue by DenesNagy** [WPI-AIM/ros_falcon#5]
Compiler does not recognize the isnan function at the following lines:
falcon_cs_pid.cpp line 158
falcon_js_pid.ccp line 156
```cpp
if(::isnan(LegAngles[i]))
```
Possible solution is to modify the lines to use the explicit std::isnan.
```cpp
if(std::isnan(LegAngles[i]))
```

**Comment by adnanmunawar** [comment]
Thanks, I agree
