### ISSUE TITLE
How to Compile all nodes

### ISSUE THREAD

**Issue by jcorredorc** [WPI-AIM/ros_falcon#7]
Hi, 
As far as I understand, the package consist of  examples to send position data to the Falcon. However, I would like to have a node that sends force and can read the position of the falcon. I think this can be done with the driver.cpp node. But this file is not compiled by default, at least in my case. When I build the package get only this nodes by default:

**falcon_control,  falcon_js_pid,   joystick, falcon_cs_pid,   gripper**

I tried to compile this file  (drive.cpp) by adding it to the Cmakelists.txt file and change the lines # 12 y 13, to: #include <ros_falcon/falconPos.h>, #include <ros_falcon/falconForces.h>, but I get this error,

```
Errors << ros_falcon: make ~/catkin_ws/logs/ros_falcon/build.make.003.log
~/catkin_ws/src/ros_falcon/src/driver.cpp: In function 'bool init_falcon (int)':
~/catkin_ws/src/ros_falcon/src/driver.cpp:103:57: error: no matching function for call to 'libnifalcon :: FalconFirmware :: setForces (boost :: array <int, 3u> &)'
     m_falconDevice.getFalconFirmware () -> setForces (forces);
......
```
Could you tell me if I'm on the right way? and how could I build this node ? What am I not considering?

thanks in advance!

**Comment by adnanmunawar** [comment]
I am using ssh from home so I can't test the applicaiton but I modified the driver.cpp and CMake to allow succeful compilation. The changes are on the devel branch now, can you please check it out and let me know if it works. We can take it forward form there.

https://github.com/WPI-AIM/ros_falcon/commit/4aa4b5580c6c5099e01b014a82dda269c3b3e284
